ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

default_language_version:
  node: 16.15.0

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: check-yaml
  - id: mixed-line-ending

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
